import { StyleSheet } from "react-native"
const styles = StyleSheet.create({
    root:{
      backgroundColor:'#ffffff',
      paddingVertical:20,
    },
    container:{
      paddingHorizontal:30
    },
    productListCont:{
      marginBottom:20
    },
    title:{
      color:"#707070",
      fontSize:22,
      fontWeight:"600",
      borderBottomColor:"#d1d1d1",
      borderBottomWidth:1,
      paddingBottom:5
    },
    cartList:{
      backgroundColor:"#f1f1f1",
      height:300,
      borderTopWidth:1,
      borderBottomWidth:1,
      borderBottomColor:"#707070",
      borderTopColor:"#707070",
    },
    chargeName:{
      color:"#707070",
      fontSize:16
    },
    amount:{
      color:"#707070",
      fontSize:16
    },
    chargeCont:{
      flexDirection:"row",
      justifyContent:"space-between",
      alignItems:'center',
      paddingVertical:10,
    },
    orderCharges:{
      borderBottomColor:"#d1d1d1",
      borderBottomWidth:1,
  
    },
    totalChargesCont:{
      flexDirection:"row",
      justifyContent:"space-between",
      alignItems:'center',
      paddingVertical:10,
    },
    totalChargeAmount:{
      fontSize:20,
      color:"#8e80ff",
      fontWeight:"600"
    },
    totalChargeName:{
      fontSize:20,
      color:"#8e80ff",
      fontWeight:"600"
    },
    paymentType:{
      backgroundColor:'#f1f1f1',
      paddingVertical:20,
      marginVertical:30
    },
    btnCont:{
      flexDirection:"row",
      marginBottom:50,
    }
  })

  export default styles