import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
    root:{
    },
    selectedProduct:{
       flexDirection:'row',
       paddingHorizontal:10,
       paddingVertical:20,
       backgroundColor:'#ffffff',
       borderTopColor:'#d1d1d1d1',
       borderTopWidth:1
    },
    leftSection:{
       flex:1
    },
    productImage:{
       width:60,
       height:70,
       resizeMode:'contain',
       alignSelf:'center',
       marginBottom:5
    },
    productName:{
       textAlign:'center',
       color:'#000000',
       fontSize:14,
    },
    rightSection:{
       flex:3,
       flexDirection:'row',
       justifyContent:'space-around',
       alignItems:'center'
    },
    cartTotal:{
       backgroundColor:'#8e80ff',
       flexDirection:'row',
       justifyContent:'space-between',
       paddingHorizontal:20,
       alignItems:'stretch',
       height:80
    },
    proceedBtn:{
       flexDirection:'row',
       alignItems:'center',
       justifyContent:'center',
       paddingLeft:30
    },
    proceedBtnContent:{
       flexDirection:'row',
       alignItems:'center'
    },
    proceedBtnText:{
       color:'#ffffff',
       fontSize:22,
       marginRight:10,
       fontWeight:'600'
    },
    proceedBtnIcon:{
       color:'#ffffff'
    },
    details:{
       flexDirection:'column',
       justifyContent:'center',
    },
    mdWhite:{
       color:'#ffffff',
       fontSize:16,
    },
    lgWhite:{
       color:'#ffffff',
       fontSize:22
    },
    cost:{
       flexDirection:'row',
       alignItems:'flex-end'
    }
})

export default styles