export const POST_NEW_ORDER_SUCCESS = 'POST_NEW_ORDER_SUCCESS';
export const POST_NEW_ORDER_FAILED = 'POST_NEW_ORDER_FAILED';
export const POST_NEW_ORDER_PENDING = 'POST_NEW_ORDER_PENDING';

export const FETCH_ALL_ORDERS_SUCCESS = 'FETC_ALL_ORDERS_SUCCESS';
export const FETCH_ALL_ORDERS_PENDING = 'FETC_ALL_ORDERS_PENDING';
export const FETCH_ALL_ORDERS_FAILED = 'FETC_ALL_ORDERS_FAILED';

export const DELETE_CURRENT_ORDER = 'DELETE_CURRENT_ORDER'

export const UPDATE_ORDER_PAYMENT_METHOD = 'UPDATE_ORDER_PAYMENT_METHOD';
export const UPDATE_ORDER_PAYMENT_PROOF = 'UPDATE_ORDER_PAYMENT_PROOF';
export const UPDATE_ORDER_PRODUCT_LIST = 'UPDATE_ORDER_PRODUCT_LIST';

export const SET_ORDER_STATE = 'SET_ORDER_STATE'