
export const  GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const  GET_PRODUCTS_FAILED='GET_PRODUCTS_FAILED'
export const  GET_PRODUCTS_PENDING='GET_PRODUCTS_PENDING'
export const  GET_CATEGORIES_SUCCESS='GET_CATEGORIES_SUCCESS'
export const  GET_CATEGORIES_FAILED='GET_CATEGORIES_FAILED'
export const  GET_CATEGORIES_PENDING='GET_CATEGORIES_PENDING'
